### ISSUE TITLE
🟠The process to create an account does not finish if the user does not have balance

### ISSUE THREAD

**Issue by camimancusi** [protofire/ink-multisig-ui#88]
Description
When you try to create an account without having balance, the process does not finish. It keeps in a loop

Browser
Google Chrome Version 119.0.6045.200

Deployment-version
[Tx Builder Stepper](https://github.com/protofire/ink-multisig-ui/commit/a26f9db41eb911300435535b60bd97542a85d5b3)

Expected result
If the user does not have enough balance to create an account, there should be an error message in the account creation and a button to let him retry

Obtained result
The account creation keeps in a loop as you see in the image
![image](https://github.com/protofire/ink-multisig-ui/assets/103962159/8f889e41-1be2-48b8-bc6c-9756edf1e557)

Severity
🔴Critical
🟠High
🟡Medium
🟢Minor

**Comment by henrypalacios** [comment]
Closed by #136
