### ISSUE TITLE
🟡[Send Tokens] The error thrown after trying to send psp22 withou SBY is not clear for the user

### ISSUE THREAD

**Issue by camimancusi** [protofire/ink-multisig-ui#95]
Description
If the multisig does not have SBY, the transfer can not be complete and the error shown in the UI is not clear for the user

![image](https://github.com/protofire/ink-multisig-ui/assets/103962159/79e746bb-4fda-469e-a50e-8e34ca93b950)

Browser
Google Chrome Version 119.0.6045.160

Deployment-version
https://github.com/protofire/ink-multisig-ui/commit/bf20e243e7983016878274af60e0420b8458adf1

Expected result
The error should be easy to read and undertand for the user

Obtained result
The error is not clear

Severity
🔴Critical
🟠High
🟡Medium
🟢Minor

**Comment by 0xLucca** [comment]
Fixed
![image](https://github.com/protofire/ink-multisig-ui/assets/95830307/20136c3f-75f7-4095-a59f-da898ff32d9b)
